import { Inter } from "next/font/google";
import { Dashboard } from "./components/Dashboard";
// import "./globals.css";
import "../app/components/style.css";
import { Header } from "./components/Header";
import { RightSide } from "./components/RightSide";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Dashboard />
          <div className="childrenBox">{children}</div>
          <RightSide />
        </div>
      </body>
    </html>
  );
}
